export const QUERY_KEYS = Object.freeze({
  TOKEN: 'token',
  USER_INFO: 'userInfo',
  WELFARES: 'welfares',
  DISTRICTS: 'districts',
  CURRENT_LOCATION: 'currentLocation',
  CLOSEST_WELFARES: 'closestWelfares',
  MEMBERSHIPS: 'memberships',
  COURSES: 'courses',
  ENROLLMENTS: 'enrollments',
  LOST_ITEMS: 'lostItems',
  MEALS: 'meals',
  ROOMS: 'rooms',
  MESSAGES: 'messages',
  COMMENTS: 'comments',
  FEED_POSTS: 'feedPosts',
});
