name: Release Server App Docker

on:
  pull_request:
    paths:
      - 'packages/server/**'
    types:
      - closed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.server
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_SERVER }}:server-latest

      - name: SSH into EC2 and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            CONTAINERS=$(sudo docker ps -a -q --filter "ancestor=${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO_SERVER}}:server-latest")
            for CONTAINER_ID in $CONTAINERS
            do
                sudo docker rm -f $CONTAINER_ID
            done
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO_SERVER}}:server-latest
            sudo docker run \
            -e MONGODB_URL=${{ secrets.MONGODB_URL }} \
            -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }} \
            -e KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }} \
            -d -p 8000:8000 \
            --name ${{secrets.DOCKERHUB_REPO_SERVER}} ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO_SERVER}}:server-latest
            sudo docker image prune -f
